### ISSUE TITLE
how do i get this to work and install

### ISSUE THREAD

**Issue by tjw0lf** [pulb/mailnag#136] opened 2016-09-27 17:58 UTC
How to i get mailnag to work and install with GNOME extension. Does this still work using newest GNOME 3.20 newest

**Comment by pulb** [comment] 2016-09-27 20:57
Yes, this works with GNOME until 3.22.
Did you read the [README](https://github.com/pulb/mailnag/blob/master/README.md)?

**Comment by tjw0lf** [comment] 2016-09-27 21:04
Ya i read it. I installed the one from my distro like said. How do i get the icon on the panel for GNOME. Its not there

**Comment by tjw0lf** [comment] 2016-09-27 21:06
Also what mail should i be going through from GNU app. Its using evolution mail but i put in gmail.

**Comment by pulb** [comment] 2016-09-27 21:09
Ok, I take a wild guess and assume you're on Arch Linux and installed it from AUR.
- Did you install the gnome-shell extension?
- Did you enable the extension in gnome-tweak tool?
- Is Mailnag set up correcly and running (see _Troubleshooting_ in the README)

**Comment by pulb** [comment] 2016-09-27 21:13
As stated in the README, you have to set your default mail client in GNOME. For gmail you need a tool like gnome-gmail and set this as default mail client.

**Comment by tjw0lf** [comment] 2016-09-27 21:20
No sorry. I'm running openSUSE tumbleweed GNOME. And i installed Mailnag throught the software manager its 1.2.

The GNOME extension has an error so i might not have manually put the right info when copying and paste it to the /.local/share/gnome.shell/extension/

I have to manually do it because the extension doesn't work for some reason when i flip the install on on GNOME site

Here's the error i get when turning it on in gnome-tweak-tool

`GLib.FileError: Failed to open file '/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  getSettings@/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/convenience.js:81
  MailnagSettingsWidget<._init@/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/prefs.js:46
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/tj/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/prefs.js:99
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1`

**Comment by pulb** [comment] 2016-09-27 21:23
I see. The compiled schemas file is missing.
```
cd <extension_folder>/schemas  
./glib-compile-schemas
```

**Comment by pulb** [comment] 2016-09-27 21:28
Sorry , the code above was wrong. I just corrected it.

**Comment by tjw0lf** [comment] 2016-09-27 21:44
How do i fix it

**Comment by pulb** [comment] 2016-09-27 21:46
By entering the two commands above in a terminal..

**Comment by tjw0lf** [comment] 2016-09-27 21:47
There's only one command

cd ~/.local/share/gnome-shell/extensions/mailnag\@pulb.github.com/schemas  
glib-compile-schemas .

**Comment by pulb** [comment] 2016-09-27 21:49
1. cd into that folder
2. run glib-compile-schemas .

**Comment by tjw0lf** [comment] 2016-09-27 21:53
What i'm i doing wrong thats not doing anything

Here's what i have in terminal
tj@wolf:~> cd ~/.local/share/gnome-shell/extensions/mailnag\@pulb.github.com/schemas
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas> ls
gschemas.compiled  org.gnome.shell.extensions.mailnag.gschema.xml
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas> glib-compile-schemas 
You should give exactly one directory name
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas> glib-compile-schemas .
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas> ls
gschemas.compiled  org.gnome.shell.extensions.mailnag.gschema.xml
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas> ./glib-compile-schemas
bash: ./glib-compile-schemas: No such file or directory
tj@wolf:~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas>

**Comment by pulb** [comment] 2016-09-27 21:57
It's all fine now. You just have to restart gnome-shell. ("glib-compile-schemas ." was the correct command)

**Comment by tjw0lf** [comment] 2016-09-27 22:08
OK its working the extension. 

How do i get the mail to show up in the panel. Its showing for Evolution but not on the panel. Also how to get avatar picture. I'm using gmail

**Comment by tjw0lf** [comment] 2016-09-27 22:44
The mail isn't coming up on the panel

**Comment by tjw0lf** [comment] 2016-09-27 23:10
OK mail is working it just took some time because i let everything sit in my mail i have over 6000 mails lol

I just want to know how you get the avatar up like in screenshot

**Comment by pulb** [comment] 2016-09-28 06:44
Yes, Mailnag fetches unread mail, so if you have 6000 unread mails it has to crawl trough all of them. As a solution remove unneeded mails or at least mark seen mails as read in your email client.

For avatar support you need mailnag-gnome-shell with avatar support enabled (your copied extension does not have it). Since Open Suse does not seem to provide such a package, you need to compile it yourself as described [here](https://github.com/pulb/mailnag-gnome-shell/blob/master/README.md) (pretty easy).

Avatars are fetched from gnome-contacts and social media sites like Google+ or Facebook so you need to add avatar photos to your contacts in gnome-contacts or enable Google+ or Facebook accounts in gnome-online-accounts.

**Comment by tjw0lf** [comment] 2016-09-28 17:40
Thanks pulb. I just totally started fresh and wiped all my mail out. So now i'm good :)

SO how would i complie it. I think i trid it and didn't work i must have done it wrong. what do i need to grab

**Comment by tjw0lf** [comment] 2016-09-28 17:59
tj@wolf:~/git_projects/mailnag-gnome-shell-3.20.0> make install-local
valac --pkg folks aggregate-avatars.vala
folks.vapi:117.4-117.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:132.4-132.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:140.4-140.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:158.4-158.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:201.4-201.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:203.4-203.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:212.4-212.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:243.4-243.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:278.4-278.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:334.4-334.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
folks.vapi:571.4-571.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:267.4-267.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:662.4-662.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:664.4-664.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:672.4-672.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-0.8.vapi:674.4-674.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
aggregate-avatars.vala:35.2-35.19: warning: implicit .begin is deprecated
error: Failed to execute child process "cc" (No such file or directory)
Compilation failed: 1 error(s), 17 warning(s)
make: *** [Makefile:14: aggregate-avatars] Error 1
tj@wolf:~/git_projects/mailnag-gnome-shell-3.20.0>

**Comment by pulb** [comment] 2016-09-28 18:09
I have no idea what's wrong here. What does `gcc --help` say?

**Comment by tjw0lf** [comment] 2016-09-28 18:25
gcc wasn't installed.

I think it did it but not sure i still don't have avatar. i restart gnome no avatar

In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/tj/mailnag-gnome-shell-3.20.0/aggregate-avatars.vala.c:28:
/home/tj/mailnag-gnome-shell-3.20.0/aggregate-avatars.vala.c: In function ‘string_strip’:
/home/tj/mailnag-gnome-shell-3.20.0/aggregate-avatars.vala.c:84:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^~~~~~
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar * {aka char *}’ but argument is of type ‘const gchar * {aka const char *}’
 gchar*                g_strchug        (gchar        *string);
                       ^~~~~~~~~
/home/tj/mailnag-gnome-shell-3.20.0/aggregate-avatars.vala.c: In function ‘__lambda4_’:
/home/tj/mailnag-gnome-shell-3.20.0/aggregate-avatars.vala.c:158:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     _tmp17_ = _tmp16_;
             ^
/home/tj/mailnag-gnome-shell-3.20.0/aggregate-avatars.vala.c:210:16: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
        _tmp36_ = _tmp35_;
                ^
Compilation succeeded - 17 warning(s)
test -d ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com || mkdir --parents ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com
for p in aggregate-avatars; do \
	install -m 0755 $p ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com; \
done
for d in extension.js indicator.js utils.js convenience.js prefs.js opts.js stylesheet.css metadata.json; do \
	install -m 0644 $d ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com; \
done
test -d /usr/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas || mkdir --parents ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas
for d in schemas/org.gnome.shell.extensions.mailnag.gschema.xml; do \
	install -m 0644 $d ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas; \
done
glib-compile-schemas ~/.local/share/gnome-shell/extensions/mailnag@pulb.github.com/schemas
tj@wolf:~/mailnag-gnome-shell-3.20.0>

**Comment by tjw0lf** [comment] 2016-09-28 18:27
I have google+ coming up but no avatar

**Comment by pulb** [comment] 2016-09-28 18:41
Try to assign a photo to the contact you receive the email from in gnome-contacts.

**Comment by tjw0lf** [comment] 2016-09-28 18:59
What about Google+ how do i get avatars to show up with that

**Comment by pulb** [comment] 2016-09-28 19:06
I guess your contacts need to have a Google+ account and must have registered the same email address they send you a message from. 

If you added a Google (not Google+!) account in gnome-online-accounts, mailnag-gnome-shell may also use the photos you assigned in the address book on your phone.

**Comment by tjw0lf** [comment] 2016-09-28 19:11
OK i did Test with my other gmail account and sent it to my email they both have avatars in gnome-contects.

Its not showing up on the panel

**Comment by pulb** [comment] 2016-09-28 19:14
Did you try to restart the extension? Did you enable avatars in the extension settings dialog?

**Comment by tjw0lf** [comment] 2016-09-28 19:21
yes i flippit it off then back on and the avatar is checked. I even restarted gnome.

**Comment by pulb** [comment] 2016-09-28 19:24
Maybe it's broken in current GNOME - I didn't test recently. Please close this bug report and open a new one in the mailnag-gnome-shell project.

**Comment by tjw0lf** [comment] 2016-09-28 19:29
OK

**Closed** 2016-09-28 19:31 UTC

**Comment by pulb** [comment] 2016-09-28 19:58
Sorry, can't reply via email to the new bug report so I'm replying here again. Just noticed libfolks(the backend for avatar aggregatetion) is split up in multiple packages in tumbleweed. Try to install all of them (libfolks-*)

**Comment by tjw0lf** [comment] 2016-09-28 20:23
This is everything it shows for folks

[URL=http://www.imagebam.com/image/9bea2b506879245][IMG]http://thumbnails116.imagebam.com/50688/9bea2b506879245.jpg[/IMG][/URL]

**Comment by pulb** [comment] 2016-09-28 20:40
Looks ok to me (except that Google+ requires libfolks-socialweb which is obviously not available in tumbleweed). So the problem is probably something different..

**Comment by tjw0lf** [comment] 2016-09-28 20:51
Well even the contents weren't showing avatar. When i did a test and i had avatar for both my emails i sent to myself. So most likely i'm missing packages from openSUSE. If this is the case i will be trying Arch to see

**Comment by pulb** [comment] 2016-09-28 20:59
I'd suggest to not waste further time on this. I've got the feeling they changed something in libfolks and I have to adapt the code of the extension. I'm gonna report progress on the issue in the new bug report when I find time for further investigations.

**Comment by tjw0lf** [comment] 2016-09-28 21:02
OK let me know when you have it updated. Or find the answer

**Comment by tjw0lf** [comment] 2016-10-02 16:17
OK i'm getting this error again. I redownload the git mail.gnome-shell.
