### ISSUE TITLE
Checking mails is broken when folders are selected

### ISSUE THREAD

**Issue by HeikoAdams** [pulb/mailnag#108] opened 2015-12-13 18:17 UTC
If a mail-account is configured to check specific folders (checkbox "activate Push-IMAP" is grayed out) an ecception is raised when mailnag tries to look for new mails:

> Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mailnagdaemon.py", line 183, in _start
    self._mailchecker.check(self._accounts)
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mailchecker.py", line 58, in check
    all_mails = self._mailsyncer.sync(accounts)
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mails.py", line 278, in sync
    rcv_lst = MailCollector(self._cfg, accounts).collect_mail(sort = False)
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mails.py", line 115, in collect_mail
    conn.close()
  File "/usr/lib/python2.7/site-packages/Mailnag/common/imaplib2.py", line 669, in close
    raise self.error('No mailbox selected.')
error: No mailbox selected.

**Comment by pulb** [comment] 2015-12-14 18:21
Hi, I suppose you're using Mailnag from git? Looks like some of your folders don't exist. Do you get a warning message before this traceback? Like 'folder does not exist'?

**Comment by HeikoAdams** [comment] 2015-12-14 21:33
Yes, I'm using latest git snapshot and the folders **should** exist because they are used by serverside filters :wink:

**Comment by HeikoAdams** [comment] 2015-12-14 22:10
Yes, there a some "folder does not exist" error before that traceback. The funniest one is
> WARNING (2015-12-14 23:06:33): Folder (\HasChildren) "." "INBOX" does not exist.

because **that folder** definitely exists :wink:

**Comment by pulb** [comment] 2015-12-14 22:14
Arghh.. this "HasChildren" token looks like a parsing error in the new folder selector code. Thanks for reporting!

**Comment by pulb** [comment] 2015-12-20 13:06
I'm unable tor reproduce your issue. Is this __(\HasChildren) "." "INBOX"__ string also displayed in the folder list in mailnag-config or does it just say "INBOX? Which email provider are you using?

**Comment by HeikoAdams** [comment] 2015-12-20 15:31
My mails and domains are hosted at a DomainFactory reseller.

**Comment by HeikoAdams** [comment] 2015-12-20 15:32
![bildschirmfoto von 2015-12-20 16-32-11](https://cloud.githubusercontent.com/assets/1418818/11918574/45bac2b8-a737-11e5-9f11-d184963c1227.png)

**Comment by pulb** [comment] 2015-12-20 15:59
Ok, that looks definitely wrong :anguished: 
Can you please add `print s` to line 108 of common/accounts.py, start mailnag-config in a terminal, open the folder list and copy/paste the output here?

**Comment by pulb** [comment] 2015-12-20 16:00
(oh and accounts.pyc should probably be deleted too)

**Comment by pulb** [comment] 2015-12-20 16:02
It should actually look like this:

![bildschirmfoto von 2015-12-20 17-01-42](https://cloud.githubusercontent.com/assets/827576/11918677/69606a02-a73b-11e5-8e7e-31900f55597b.png)

**Comment by HeikoAdams** [comment] 2015-12-20 16:14
>(\HasChildren) "." "INBOX"
(\HasChildren) "." "INBOX.Archives"
(\HasNoChildren) "." "INBOX.Archives.2015"
(\HasNoChildren) "." "INBOX.Archives.2014"
(\HasNoChildren) "." "INBOX.Junk E-Mail"
(\HasNoChildren) "." "INBOX.Soziale Netzwerke"
(\HasNoChildren) "." "INBOX.Templates"
(\HasNoChildren) "." "INBOX.Trash"
(\HasNoChildren) "." "INBOX.Stellensuche"
(\HasNoChildren) "." "INBOX.Drafts"
(\HasNoChildren) "." "INBOX.Sent"

**Comment by pulb** [comment] 2015-12-20 19:10
Thanks, should be fixed now.

**Comment by HeikoAdams** [comment] 2015-12-20 20:28
Yes, it's fixed and works fine. Thanks!

**Closed** 2015-12-21 17:33 UTC
